IBM/network-config-analyzer

- Dockerfile
> NCA in container should not run as root

- .github/workflows/test-push-live-k8s-cluster.yml
- network-config-analyzer/ConnectivityGraph.py
- network-config-analyzer/nca.py
- tests/cmdline_live_k8s_tests.yaml
- tests/run_live_k8s_tests.py
Added a new workflow to test live k8s cluster. Need to add it to master in order to be able to manually debug it
> Live k8s test

- network-config-analyzer/CLExecute.py
- network-config-analyzer/PeerContainer.py
- network-config-analyzer/SchemeRunner.py
- network-config-analyzer/nca.py
- tests/cmdline_tests.yaml
- tests/example_policies/tests-different-topologies/semanticDiff-multiple-resources-scheme.yaml
> supporting multiple pod_resources files 

- network-config-analyzer/NetworkConfig.py
- network-config-analyzer/RESTServer.py
> avoiding the buffer hack and using a flag instead

- .github/workflows/test-push.yml
- tekton/netpol-report-plr.yaml
- tests/tests_expected_runtime.csv
> activate testing performance in the workflow

- tests/fw_rules_tests/podlist/kubernetes-manifests-new.yaml
- tests/fw_rules_tests/podlist/kubernetes-manifests-new1.yaml
- tests/fw_rules_tests/podlist/kubernetes-manifests.yaml
- tests/run_all_tests.py
Added a delay after deploying resources in testing live cluster, to make sure all pods are up and running
> Bug in testing live cluster bug

- network-config-analyzer/DirScanner.py
- network-config-analyzer/GenericTreeScanner.py
- network-config-analyzer/GitScanner.py
- network-config-analyzer/nca.py
- tests/k8s_testcases/example_policies/withIpBlock2/withIpBlock2-scheme.yaml
- tests/run_all_tests.py
> supporting Ghe urls with raw content

- tests/run_all_tests.py
- tests/tests_expected_runtime.csv
>  updating run_all_tests script

- network-config-analyzer/DirScanner.py
> closing resources files

- network-config-analyzer/K8sPolicyYamlParser.py
- tests/k8s_testcases/network-policy-checks-bad-path/matchlabels_wrong_value_label_type.yaml
- tests/k8s_testcases/network-policy-checks-bad-path/network-policy-check-bad-path-scheme.yaml
> Issue #275: Checking that a label value is a string

- network-config-analyzer/CanonicalHyperCubeSet.py
- network-config-analyzer/K8sNamespace.py
> Issue #292: Set the kubernetes.io/metadata.name on all namespaces

- network-config-analyzer/CanonicalIntervalSet.py
> refactored __repr__ to call __str__

- network-config-analyzer/SchemeRunner.py
- tests/expected_runtime/k8s_tests_expected_runtime.csv
- tests/k8s_testcases/all_resources_in_same_dir/all-resources-in-one-dir-scheme.yaml
- tests/k8s_testcases/all_resources_in_same_dir/ns_list.json
- tests/k8s_testcases/all_resources_in_same_dir/pods_list.json
- tests/k8s_testcases/all_resources_in_same_dir/some-captured-tests-networkpolicy.yaml
Signed-off-by: shireenf-ibm <shireenf@il.ibm.com>
#291 
eliminating  `if path.exists(given_path):` fixes the bug
I couldn't find a use case that this `if` was needed for. If the path is not absolute we'll need to "build" it using the realpath of the scheme file
> bug fix of reading paths like ./ ../

- network-config-analyzer/IngressPolicyYamlParser.py
- network-config-analyzer/IstioTrafficResourcesYamlParser.py
Signed-off-by: Tanya <tatyana@il.ibm.com>
> Small fixes.

- nca/nca_cli.py
> Command-line switch for printing NCA version from VERSION.txt

- .github/workflows/test-push.yml
- nca/FWRules/ConnectivityGraph.py
- nca/NetworkConfig/NetworkConfigQuery.py
- nca/SchemeRunner.py
- nca/nca_cli.py
> Remove unused imports; stop ignoring lint rule F401

- .github/workflows/make-github-and-docker-release.yml
- .github/workflows/test-push.yml
- Dockerfile.ubi
> Also build a ubi-based Docker image

- nca/FileScanners/GenericTreeScanner.py
- nca/FileScanners/GitScanner.py
- requirements.txt
- setup.cfg
> Replace PyGithub with ghapi (has better license)

- Dockerfile.ubi
> Run yum upgrade in Dockerfile.ubi to resolve vulnerabilities

- nca/nca_cli.py
2. catch and pring exceptions + their traces
Signed-off-by: haim-kermany <haim.kermany@gmail.com>
> 1. add --debug flag

- .github/actions/setup-nca-env/action.yaml
- .github/dependabot.yml
> Upgrade setup-python action + set dependabot to scan action weekly

- .github/workflows/test-push.yml
- nca/NetworkConfig/ResourcesHandler.py
- nca/nca_cli.py
Signed-off-by: haim-kermany <haim.kermany@gmail.com>
> do not crash on maformed ymal

- nca/NetworkConfig/NetworkConfigQuery.py
- nca/SchemeRunner.py
- tests/istio_testcases/scan-dir-test-scheme.yaml
- tests/run_all_tests.py
Signed-off-by: haim-kermany <haim.kermany@gmail.com>
> issue 384 - error on empty peer container 

- nca/FileScanners/DirScanner.py
- nca/FileScanners/HelmScanner.py
- nca/NetworkConfig/ResourcesHandler.py
2. opening file with encoding='utf8'
3. expecting UnicodeDecodeError when encoding a file
Signed-off-by: haim-kermany <haim.kermany@gmail.com>
> issue-394-use-utf8-encoder

- docs/SchemeFileFormat.md
- nca/NetworkConfig/NetworkConfigQuery.py
- tests/calico_testcases/example_policies/testcase26-multi-layer-policies/testcase26-multi-layer-allcaptured-scheme.yaml
- tests/calico_testcases/expected_output/multi-layer-all-captured-1.json
- tests/calico_testcases/expected_output/multi-layer-all-captured-1.txt
- tests/calico_testcases/expected_output/multi-layer-all-captured-1.yaml
Issue #403 
Committed:
1. improve message when no policies are considered.
2. adding information about ingress captured with istio
Signed-off-by: shireenf-ibm <shireenf@il.ibm.com>
Signed-off-by: shireenf-ibm <shireenf@il.ibm.com>
> issue_403 - AllCaptured tasks

- .github/workflows/test-push.yml
> Jobs to build and test nca package

- nca/NetworkConfig/ResourcesHandler.py
- nca/Utils/NcaLogger.py
Signed-off-by: Shmulik Froimovich <Shmulik.Froimovich@ibm.com>
> info livesim messages fix

- nca/CoreDS/CanonicalHyperCubeSet.py
- nca/CoreDS/ConnectivityCube.py
- nca/CoreDS/DimensionsManager.py
- nca/NetworkConfig/NetworkConfigQuery.py
- nca/Resources/NetworkPolicy.py
Fixed handling of src_peers/dst_peers full domains, by updating the domain in DimensionsManager according to the current config(s).
> Better handling of src_peers/dst_peers full domains

- nca/NetworkConfig/PoliciesFinder.py
- nca/NetworkConfig/TopologyObjectsFinder.py
- nca/Parsers/IstioGatewayPolicyGenerator.py
- nca/Parsers/IstioVirtualServiceYamlParser.py
- nca/Resources/OtherResources/VirtualService.py
- nca/Resources/PolicyResources/GatewayPolicy.py
- nca/Utils/ExplTracker.py
- tests/expected_runtime/istio_tests_expected_runtime.csv
Added origin path/line information to istio gateway policies, for explainability report.
> Istio gateway policies explainability information
